### ISSUE TITLE
Support `import.meta.resolve`

### ISSUE THREAD

**Issue by pi0** [unjs/jiti#101]
We shall polyfill it to allow upgrading from `require.resolve`

```js
(function (exports, require, module, __filename, __dirname) { "use strict";console.log(import.meta.resolve('./a.ts'));
                                                                                              ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
```

**Comment by kungpaogao** [comment]
I'm seeing a similar error but with `import.meta.env`, but saw this issue already existed - is this related, or is there another workaround for using `import.meta.env`? I'm able to get it to work if I use `process.env`, but then I use the scripts in a Vite/Astro project, so I would have to maintain both versions?
