### ISSUE TITLE
Parameter Decorators leads to error "Cannot read properties of undefined (reading 'prototype')"

### ISSUE THREAD

**Issue by mav-rik** [unjs/jiti#103]
### Environment

node v18, jiti v1.16.0

### Reproduction

Bug appears when using method & parameter decorator together like:
```ts
class MyApp {
    @Get('test')
    test(@Query() query) {
        // ...
    }
}
```

### Describe the bug

The plugin `babel-plugin-parameter-decorator` generates a buggy piece of code that leads to an error "Cannot read properties of undefined (reading 'prototype')"

The problem is mentioned [here](https://github.com/WarnerHooh/babel-plugin-parameter-decorator/issues/34#issuecomment-1074930057).

The author of `babel-plugin-parameter-decorator` doesn't seem to want to fix it.

The solution proposed [here](https://github.com/WarnerHooh/babel-plugin-parameter-decorator/issues/34#issuecomment-1197579824).

### Additional context

As a solution I suggest to switch from `@babel/plugin-proposal-decorators` & `babel-plugin-parameter-decorator` to proposed `babel-plugin-typescript-decorators`.

### Logs

```
TypeError: Cannot read properties of undefined (reading 'prototype')
```

**Comment by pi0** [comment]
We have ported a fixed fork of plugin for jiti v2. LMK if experienced any issues with it 👍🏼
