### ISSUE TITLE
Release for `satisfies` operator support

### ISSUE THREAD

**Issue by sxzz** [unjs/jiti#106]
### Environment

N/A

### Reproduction

N/A

### Describe the bug

Please bump a new version for `satisfies` operator support

It's already supported via https://github.com/unjs/jiti/commit/e79ba40f3db92d250228cb14434d550cbafe88e1

**Comment by pi0** [comment]
Released 1.16.1. I hope it adds support 👍🏼  (PR welcome to add fixture)

**Comment by sabinmarcu** [comment]
Thank you, @pi0 , fixed the issue for me 🙏 

Made a PR for adding a fixture for the keyword. Hope it helps (let me know if I need to do anything other than what's already in the PR)
