### ISSUE TITLE
Fatal error with v1.16.1: Cannot find module 'node:module'

### ISSUE THREAD

**Issue by dockleryxk** [unjs/jiti#109]
### Edit: Workarounds
If possible, update to Node 16 or higher (thanks @fanwei1991).

If you're using yarn, you can add this to your package.json (thanks @smyth64):

```json
"resolutions": { 
   "jiti": "1.16.0" 
}
```

If you're using a new enough version of NPM, you can add this to your package.json (but be aware of the [caveats](https://github.com/npm/cli/issues/5850)):

```json
"overrides": { 
   "jiti": "1.16.0" 
}
```

### Environment

Node 12.6.0 (also happens on Node 14.17)

### Reproduction

Installing nuxt on a fresh docker container

### Describe the bug

This is pretty much identical to #48

### Logs

```sh
FATAL  Cannot find module 'node:module'
  Require stack:
  - xxx/my-project/node_modules/jiti/dist/jiti.js
  - xxx/my-project/node_modules/jiti/lib/index.js
  - xxx/my-project/node_modules/@nuxt/utils/dist/utils.js
  - xxx/my-project/node_modules/@nuxt/cli/dist/cli-index.js
  - xxx/my-project/node_modules/@nuxt/cli/dist/cli.js
  - xxx/my-project/node_modules/nuxt/bin/nuxt.js
```

**Comment by tidusvn05** [comment]
i same for jiti@1.16.1 on docker gitlab

**Comment by llambeau** [comment]
Fixing it for me:

**Comment by sanjeet2009** [comment]
Same for me on Gitlab. 
`> nuxt build --modern=server
 FATAL  Cannot find module 'node:module'
Require stack:
- /app/node_modules/jiti/dist/jiti.js
- /app/node_modules/jiti/lib/index.js
- /app/node_modules/@nuxt/utils/dist/utils.js
- /app/node_modules/@nuxt/cli/dist/cli-index.js
- /app/node_modules/@nuxt/cli/dist/cli.js
- /app/node_modules/nuxt/bin/nuxt.js
  Require stack:
  - node_modules/jiti/dist/jiti.js
  - node_modules/jiti/lib/index.js
  - node_modules/@nuxt/utils/dist/utils.js
  - node_modules/@nuxt/cli/dist/cli-index.js
  - node_modules/@nuxt/cli/dist/cli.js
  - node_modules/nuxt/bin/nuxt.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
  at Function.Module._load (internal/modules/cjs/loader.js:745:27)
  at Module.require (internal/modules/cjs/loader.js:961:19)
  at require (internal/modules/cjs/helpers.js:92:18)
  at node_modules/jiti/dist/jiti.js:1:215[165](https://git.internetbrands.com/cdchelios/cdc-master-project/-/jobs/369418#L165)
  at node_modules/jiti/dist/jiti.js:1:249320
  at Object.<anonymous> (node_modules/jiti/dist/jiti.js:1:249367)
  at Module._compile (internal/modules/cjs/loader.js:1072:14)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
  at Module.load (internal/modules/cjs/loader.js:937:32)
   ╭─────────────────────────────────────────────────────╮`

**Comment by vietanh74** [comment]
@dockleryxk i think your NodeJS version is <= 12, upgrade node or fix `"jiti": "1.16.0"` to resolve it.
`node:` in new syntax in nodejs.

**Comment by remirobichet** [comment]
As mentioned @dockleryxk this error is similar to #48
@pi0 fixed it by removing `mlly` package.
Isn't it still related to `mlly` ? Package have been updated to v1.0.0 in jiti 1.16.1

https://github.com/unjs/jiti/blob/4d6b20d77190d08b1e72896d95abc02b8478ae0e/package.json#L60

**Comment by smyth64** [comment]
I also have the same problem since today, cannot deploy my app anymore :o

**Comment by smyth64** [comment]
The problem is the jiti update.

I fixed it by using the previous jiti version on nuxt utils :)

`  
"resolutions": {
    "nuxt/@nuxt/utils/jiti": "1.16.0"
  },
`

**Comment by dockleryxk** [comment]
@vietanh74 I can confirm the same thing happens on Node 14 and 16.

Adding the resolutions works only for yarn, and there is an overrides field for newer versions on NPM (albeit with [caveats](https://github.com/npm/cli/issues/4232)), but that isn't a great solution in the long term.

In the short term, we're using yarn resolutions while we wait for a fix.

@pi0 thank you for your work on this package!

**Comment by fanwei1991** [comment]
I also encountered this problem. node 14.17.0 was unavailable. After upgrading node to 16, this problem was removed

**Comment by daglenn1960** [comment]
Encountered this issue as well. Doing these did not work:
- reverting to jiti 1.14.0
- updating to node 16.16.0

Fix was both:
- adding override (as above) [jiti 1.16.0]
- updating to node 16.16.0

**Comment by weiyuanraoan** [comment]
> I also encountered this problem. node 14.17.0 was unavailable. After upgrading node to 16, this problem was removed

**Comment by freezyh** [comment]
> ```json
> "overrides": { 
>    "jiti": "1.16.0" 
> }
> ```

it not works
"overrides": { 
   "jiti": "1.16.0" 
}

**Comment by xukingnie** [comment]
node 14.16.0 also have the same problem

**Comment by pi0** [comment]
`jiti@1.16.2` should work again on older Node.js versions without `node:` protocol support.

If still having issues after updating and recreating lockfile, please ping to reopen.

If possible, please try upgrading Node.js to the latest 16.x or 18.x LTS.
