### ISSUE TITLE
Reflect Metadata

### ISSUE THREAD

**Issue by tada5hi** [unjs/jiti#118]
### Environment

Nodejs: v16.16.0
Jiti Version: 1.17.1

### Reproduction

Try to transpile any code with decorators which depend on dependency injection (e.g. typeorm, ..)

### Describe the bug

At the moment the implementation just strips all types and does not emit the relative Metadata in the output code.
Therefore, we also need the plugin [babel-plugin-transform-typescript-metadata](https://www.npmjs.com/package/babel-plugin-transform-typescript-metadata) to emit decorator metadata like the typescript compiler does.

**Comment by pi0** [comment]
Hi! PR is welcome to add (please also add a minimal fixture along in)
