### ISSUE TITLE
Support `import.meta.env`

### ISSUE THREAD

**Issue by pi0** [unjs/jiti#127]
https://github.com/unjs/jiti/issues/101#issuecomment-1465363353

**Comment by pi0** [comment]
Find this beatiful lib: https://iendeavor.github.io/import-meta-env/guide/getting-started/compile-time-transform.html by @iendeavor

**Comment by pi0** [comment]
Hmm i might drop some features like dotenv.

**Comment by kungpaogao** [comment]
Thank you for adding this in! Unfortunately, I'm trying to use this right now, and I'm still getting `SyntaxError: Cannot use 'import.meta' outside a module`. Am I using this incorrectly?

Just running `yarn jiti index.ts` where `index.ts` is just `console.log(import.meta.env)`.

**Comment by pi0** [comment]
Yes, the way currently plugin works is that you need explicit `import.meta.env.SOMETHING1` to be set. `import.meta.env` itself won't be transformed (we could support this btw..)
