### ISSUE TITLE
How to configure alias in jiti? Is there any detailed documentation?

### ISSUE THREAD

**Issue by szmxx** [unjs/jiti#166]
### Describe the feature

I want to use @ instead of ./src, for example @/utils is equivalent to ./src/utils

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
It is possible using `alias` config or ([JITI_ALIAS](https://github.com/unjs/jiti#alias)). 

tsconfig and other external configs are not infered (sorry i know it might feel a downside DX) but it is important to make jiti behavior portable and predictable.

Additionally since we use ESM resolution, node.js `imports` in `package.json` will be also respected for another way of setting aliases.

**Comment by alSergey** [comment]
Hi @pi0, I'm using `jiti@v2` in my project and ran into the same issue. I'd really like to configure jiti to support [tsconfig.paths](https://www.typescriptlang.org/tsconfig/#paths). Unfortunately, I haven’t found any existing solution to achieve this.

The main problem is that jiti currently supports aliases as `Record<string, string>`, whereas `tsconfig` defines them as `Record<string, string[]>`.

I wanted to ask if you'd consider improving jiti to support working with tsconfig.paths. Here are a few possible ideas:

1. **Introduce a `tsconfigPaths` flag**, which defaults to `false`. I saw [your comment here](https://github.com/unjs/jiti/issues/166#issuecomment-2374322954) where you mentioned you want to avoid relying on external config files to keep jiti predictable. That totally makes sense. But maybe if it’s a disabled-by-default flag, we can preserve that predictability while still giving devs the option to enhance their DX if needed?

2. **Extend the alias config to support `Record<string, string | string[]>`**. This would allow devs to use external libraries like [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) to read the aliases and pass them to jiti.

Thanks in advance! I hope it will be possible to introduce some improvements to jiti to support working with [tsconfig.paths](https://www.typescriptlang.org/tsconfig/#paths). At the moment, the DX really suffers without this feature.

**Comment by pi0** [comment]
An opt-in feature to support ts aliases is acceptable. Do you mind to open a new issue to track?

**Comment by alSergey** [comment]
Hi, I started a separate [issue](https://github.com/unjs/jiti/issues/373).
