### ISSUE TITLE
experimentalDecorators

### ISSUE THREAD

**Issue by krulod** [unjs/jiti#195]
### Environment

jiti 1.21.0
node 21.4.0

### Reproduction

https://stackblitz.com/edit/jiti-experimentaldecorators-reproduction?file=index.js%2Cmy-code.ts

Run `node index.js`

### Describe the bug

TypeScript with experimental decorators compiled by jiti uses `Reflect.metadata` although I don't need it and explicitly disable `emitDecoratorMetadata` in tsconfig

**Comment by pi0** [comment]
https://github.com/unjs/jiti/pull/165 fixes issue for v2
