### ISSUE TITLE
There is  not any documention for using alias & JITI_ALIAS

### ISSUE THREAD

**Issue by amirrezaDev1378** [unjs/jiti#209]
### Describe the change

Unfortunately, there is no proper documentation on how to use alias and JITI_ALIAS options.
It would be great if we have an example of how to use these options.

### Additional information

- [x] Would you be willing to help?

**Comment by hareland** [comment]
It is a key-value JSON object:
```bash
JITI_ALIAS='{"~/*": "./src/*"}' pnpm run cli/migrate.ts
```

You can see how it is parsed here: https://github.com/unjs/jiti/blob/main/src/options.ts
