### ISSUE TITLE
Not updating an import when reloading using chokidar

### ISSUE THREAD

**Issue by nethriis** [unjs/jiti#236]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Package Manager:  pnpm@9.0.0
------------------------------

### Reproduction

```ts
const watcher = chokidar.watch('.', { ignoreInitial: true })

watcher.on('all', () => {
  const _jiti = jiti('.', {
    interopDefault: true,
    cache: false,
    v8cache: false
  })
  const mod = _jiti('./path/to/file')
  console.log(mod)
})
```

### Describe the bug

When I create a new file the log who display `mod` displays `{}` and when I modify my file and exports something else like { type: 'opt' }, the log display `{}` to. The same when I just move a file containing export default { type: 'opt' } the log displays `{ type: 'opt' }` and when I empty the file it displays me `{ type: 'opt' }` too.

**Comment by pi0** [comment]
Hi. You should disable `requireCache` to allow HMR behavior. `cache` is for disk cache and you can even keep it enabled to leverage faster reloads (jiti will still compare the contents)

**Comment by pi0** [comment]
I noticed it is undocumented, if you had time and worked for you, PR welcome to add docs for `requireCache`

**Comment by nethriis** [comment]
Thank you, it does indeed work. I'll try to document the requireCache shortly.
