### ISSUE TITLE
Error "Cannot find module 'node:url '" after upgrading to jiti 1.21.3 in Node 14.17.6 environment

### ISSUE THREAD

**Issue by siLiang220** [unjs/jiti#243]
### Environment

- Node Version: 14.17.6

- jiti Version: 1.21.3

### Reproduction

1. Upgrade jiti to version 1.21.3 in a Node 14.17.6 environment

### Describe the bug

I upgraded jiti to version 1.21.3 in a Node 14.17.6 environment, but encountered the above error. From my understanding, this may be due to some changes in jiti version 1.21.3, possibly related to compatibility with Node versions.

**Comment by danielroe** [comment]
Would you be able to provide a minimal reproduction? 🙏

**Comment by danielroe** [comment]
You might need to upgrade to Node 14.18.0+

https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_node_imports

**Comment by siLiang220** [comment]
Thank you for your response.

**Comment by pi0** [comment]
I have added a relavant refactor (https://github.com/unjs/jiti/commit/5d877de3fc24312c870c55f7a7445cb250ac9949) but checking dist (we have [another check for it](https://github.com/unjs/jiti/blob/690b727d7c0c0fa721b80f8085cafe640c6c2a40/webpack.config.js#L32) for #109), and also locally with latest Node.js 14.x, same as @danielroe i could not reproduce...

I would suggest to upgrade to a supported Node.js version like 20 if you can.
