### ISSUE TITLE
import path resolve error with aliases + esmResolve

### ISSUE THREAD

**Issue by LoTwT** [unjs/jiti#249]
#### In stackblitz

System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm

#### c12-repro

https://stackblitz.com/edit/stackblitz-starters-2bmvpw

#### jiti-repro

https://stackblitz.com/edit/stackblitz-starters-u9wwgy

#### steps

- run `node index.js`
- change import methods in the `my.config.js`

### Describe the bug

It has a file whose path is like `middlewares/security/index.js`.

When loading files by c12 with the JITI alias, it can't resolve path `~middlewares/security` which must be `~middlewares/security/index`.

But both paths above can work in JITI.

**Comment by pi0** [comment]
Hi dear @LoTwT thanks for your nice reproductions and sorry it was hidden amongst other issues.

I have tried your jiti reproduction and it seems it _was_ and issue with jiti until 1.21.0. With latest mlly and pathe utils in `1.21.6` issue seems to be solved! ([updated blitz](https://stackblitz.com/edit/stackblitz-starters-gfkzkk?file=package.json,index.js))

You might want to try updating yourlockfile and please let me know if had any other issues.
