### ISSUE TITLE
Feature Request: rollup plugin

### ISSUE THREAD

**Issue by voorjaar** [unjs/jiti#26]
I want to use jiti to speed up packaging during development.

I can do this with sucrase,

![Screen Shot 2021-03-20 at 00 29 30](https://user-images.githubusercontent.com/69119532/111813107-bc366f00-8913-11eb-87f6-a6beb70f980d.png)

**Comment by pi0** [comment]
Hi @voorjaar. Jiti is optimized for on-demand cjs transpilation. I would suggest taking a look at [rollup-plugin-esbuild](https://github.com/egoist/rollup-plugin-esbuild) or you can use [siroc](https://github.com/unjs/siroc) for a super fast and zero-config packaging tool based on rollup and esbuild. /cc @danielroe

**Comment by voorjaar** [comment]
In fact, I am using [sucrase](https://github.com/alangpierce/sucrase) to run typescript tests and speed up packaging, and the experience is very good. But I am surprised that jiti can compile cjs so fast, good job. So it is similar to sucrase to me. You can refer to it, maybe some new ideas will burst out. I think I will close this temporarily.
