### ISSUE TITLE
Add `@babel/plugin-proposal-decorators` to `transform`

### ISSUE THREAD

**Issue by LukeCSamuel-RV** [unjs/jiti#27]
We make a lot of use of Typescript decorators in our code base.  In Nuxt 2.14 they could be used in places outside of webpack module resolution, such as Nuxt modules.  In Nuxt 2.15 they are no longer supported, because the babel instance bundled with Jiti doesn't have the `@babel/plugin-proposal-decorators` plugin.

I would propose that if `opts.ts` and ideally only when `experimentalDecorators === true` (from tsconfig), this plugin be added: `_opts.plugins!.push([require('@babel/plugin-proposal-decorators'), { legacy: true }])`

**Comment by pi0** [comment]
Hi @LukeCSamuel-RV. Thanks for issue it makes sense adding for typescript. Would you please open a pull request?

**Comment by tobiasdiez** [comment]
Could `babel-plugin-transform-typescript-metadata` also please be added so that the metadata added by these decorators can be used, say for dependency injection.

This would fix https://github.com/nuxt/typescript/issues/494.
