### ISSUE TITLE
when installing jiti: Deprecation Warning: punycode module usage

### ISSUE THREAD

**Issue by bkyerv** [unjs/jiti#274]
### Environment

node v22.4.0
jiti version: 1.21.6

### Reproduction

npm install jiti

### Describe the bug

below deprecation warning is displayed

`(node:722838) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use "node --trace-deprecation ..." to show where the warning was created)`

### Additional context

This warning suggests that the punycode module, which is being used either directly by jiti or by one of its dependencies, is deprecated in Node.js.

**Comment by pi0** [comment]
Can you please provide a reproduction?
