### ISSUE TITLE
doens't handle tsx files correctly

### ISSUE THREAD

**Issue by dylang** [unjs/jiti#309]
### Environment

2.0.0

### Reproduction

import a tsx file that has types

### Describe the bug

it ignores tsx as an extension for typescript.
https://github.com/unjs/jiti/blob/main/src/eval.ts#L35C2-L35C74

Just adding `tsx` there isn't enough, we also need to run the typescript transform before the JSX transform.
https://github.com/unjs/jiti/blob/main/src/babel.ts#L48-L71

**Comment by pi0** [comment]
Thanks for report. should be fixed in next release
