### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'default' ...

### ISSUE THREAD

**Issue by binarykitchen** [unjs/jiti#319]
### Environment

Jiti version 2.2.1 (the latest)
NodejS v22.8.0

### Reproduction

To reproduce, just install `npm install ffmpeg-static` (v5.2.0) and import it with Jiti like that:
```
import pathToFfmpeg from "ffmpeg-static";
```

This will throw this error every time:
```
TypeError: Cannot use 'in' operator to search for 'default' in /var/www/videomail/prod/source/node_modules/ffmpeg-static/ffmpeg
    at /var/www/videomail/prod/source/node_modules/jiti/dist/jiti.cjs:1:182495
    at jitiInteropDefault (/var/www/videomail/prod/source/node_modules/jiti/dist/jiti.cjs:1:183330)
    at jitiRequire (/var/www/videomail/prod/source/node_modules/jiti/dist/jiti.cjs:1:187464)
    at import (/var/www/videomail/prod/source/node_modules/jiti/dist/jiti.cjs:1:196818)
    at /var/www/videomail/prod/source/src/server/util/ffmpeg/runner.ts:3:50
    at eval_evalModule (/var/www/videomail/prod/source/node_modules/jiti/dist/jiti.cjs:1:193374)
    at jitiRequire (/var/www/videomail/prod/source/node_modules/jiti/dist/jiti.cjs:1:187618)
    at import (/var/www/videomail/prod/source/node_modules/jiti/dist/jiti.cjs:1:196818)
    at /var/www/videomail/prod/source/src/server/util/ffmpeg/encodeVideo.ts:8:44
    at async import (/var/www/videomail/prod/source/node_modules/jiti/dist/jiti.cjs:1:196812)
```

**Comment by binarykitchen** [comment]
FYI this didn't happen on Jiti v2.1.2, so this bug must have been introduced recently

**Comment by binarykitchen** [comment]
I guess, probably caused by some of these changes in this commit?
https://github.com/unjs/jiti/commit/88260477e96a3e9e2790ac26f7c9524b7c7f2410

**Comment by pi0** [comment]
Thanks for report. Investigating now, it is related to https://github.com/unjs/jiti/pull/318

**Comment by pi0** [comment]
While i can guess the issue by the error message you shared, i cannot reproduce locally. Can you somehow share a runnable repo? It can help me to pinpoint exact issue.

<img width="804" alt="image" src="https://github.com/user-attachments/assets/61e351a7-9a65-4277-bff0-faac764c511e">

**Comment by pi0** [comment]
You can verify the fix via [nightly channel](https://www.npmjs.com/package/jiti-nightly) thanks again for the report.

**Comment by binarykitchen** [comment]
Ok @pi0 thanks, I've amended `JITI_CACHE=0` to the command, yet it still crashes:

```
/home/michael-heuberger/code/binarykitchen/videomail.io ❯❯❯ JITI_CACHE=0 npm run dev:server                                                                                                                 dev ✭ ✱

> videomail.io@2.0.0 dev:server
> cross-env NODE_ENV=development ENVIRON=local nodemon --watch ./src/server --watch ./src/common --ignore **/__tests__/** --exec jiti ./src/server/index.ts

[nodemon] 3.1.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/server/**/* src/common/**/*
[nodemon] watching extensions: ts,json
[nodemon] starting `jiti ./src/server/index.ts`
TypeError: Cannot use 'in' operator to search for 'default' in /home/michael-heuberger/code/binarykitchen/videomail.io/node_modules/ffmpeg-static/ffmpeg
    at /home/michael-heuberger/code/binarykitchen/videomail.io/node_modules/jiti/dist/jiti.cjs:1:182495
    ...
```

Anyway, I'll check out your nightly channel now ...

**Comment by binarykitchen** [comment]
Yup, I just tested with the nightly channel @pi0 - that fixed it. Thanks :)

Please add more unit tests about this.

**Comment by pi0** [comment]
cool! we will eventually port interopDefault back to mlly repository which has unit tests. there are just too many edge cases that need respond fast, we had been fixing them since 5+ years ago and with jiti v2 it got harder since there is also native ESM...

**Comment by binarykitchen** [comment]
Nice.

I'm running an ancient but popular app. Trying to migrate it slowly to TypeScript/ESM, that's why these hiccups :)
