### ISSUE TITLE
support jiti.config file

### ISSUE THREAD

**Issue by pi0** [unjs/jiti#34]
Context https://github.com/nuxt/nuxt.js/issues/9350

Another option is `.jitirc` since loading can be faster without depending on CJS require and ensures serialization for cacheKey is still possible.

We can additionally support `JITI_OPTIONS` environment variable for inlining.

**Comment by dword-design** [comment]
This would be great!

**Comment by pi0** [comment]
As we are moving forward to fade-aways jiti in favor of runtime natives, customization makes less sense.
