### ISSUE TITLE
`JITI_SOURCE_MAPS` option is not included in cache params

### ISSUE THREAD

**Issue by connor4312** [unjs/jiti#347]
### Environment

Node.js 22

### Reproduction

1. Run [this file](https://github.com/KermanX/vsc-breakpoint-repro/blob/main/run.js) without any special settings. Notice there's no sourcemap for main.ts
2. In the API turn on sourcemaps, or set JITI_SOURCE_MAPS
3. Run it again. Notice there's still no sourcemap for main.ts 🐛 
4. Set JITI_FS_CACHE=0, and notice sourcemaps now work

### Describe the bug

Changing the Jiti options should invalidate any existing cache

### Additional context

Reported as an issue for the VS Code debugger in https://github.com/microsoft/vscode-js-debug/issues/2149

**Comment by pi0** [comment]
We should add a `-map` suffix [here](https://github.com/unjs/jiti/blob/ad6191f04624badf2112651217bc17008a9bde50/src/cache.ts#L30) to distinguish cache entries with map enabled.

**Comment by pi0** [comment]
Thanks for report dear @connor4312. I have merged #352 as possible fix. Can you try with [jiti-nightly](https://www.npmjs.com/package/jiti-nightly)? 🙏🏼 (you can ensure cache is updated using `JITI_DEBUG=1`. if issue persists with `+map` files still, this is not directly an issue with jiti (but tooling that wrongly skips sourcemap hint)
