### ISSUE TITLE
eisdir: illegal operation on a directory, read

### ISSUE THREAD

**Issue by lihbr** [unjs/jiti#55]
### Versions

- nuxt: v2.15.8
- jiti: v1.12.13, v1.12.12 (v1.12.11 and v1.12.10 yield a different issue)
- node: v16.13.0

**Apparently this is Windows only:**

I haven't been able to reproduce on MacOS using node v16.3.0 (then my MacBook BSOD'd as I was going to try on v16.13.0 so I gave up using this computer for now)

### Steps to reproduce

```bash
npx create-nuxt-app
npm run dev
```

### What is expected?

Nuxt should work(?)

### What is actually happening?

![image](https://user-images.githubusercontent.com/25330882/151152141-cf45fd01-8e3f-43fb-8a60-a213a6f57490.png)

Downgrading jiti to v1.12.12 yields the same issue
Downgrading jiti to v1.12.11 or v1.12.10 yield an `Unexpected token 'import'` issue
Downgrading jiti to v1.12.9 fixes the issue

Bug is likely a regression from [yesterday's changes](https://github.com/unjs/jiti/blob/main/CHANGELOG.md#11213-2022-01-25).

Cheers 💐

**Comment by pi0** [comment]
Hi @lihbr. It is likely to be a regression but I cannot reproduce it in my windows machine with node 16.13.0 and latest jiti (1.12.13). Do you maybe use a specific option of can?

<img width="560" alt="image" src="https://user-images.githubusercontent.com/5158436/151154856-917ed24f-0ad5-4dbf-9092-b6a3756847e3.png">

**Comment by lihbr** [comment]
Sure, here are mine: 
![image](https://user-images.githubusercontent.com/25330882/151155058-8659a41a-98ea-4d90-9085-f5485dcea2c2.png)

**Comment by lihbr** [comment]
The exact line that throws is this one: https://github.com/unjs/jiti/blob/HEAD/src/jiti.ts#L202, I'm investigating~

**Comment by lihbr** [comment]
OK, got it (added log for filename):
![image](https://user-images.githubusercontent.com/25330882/151155962-857ea832-8435-4f68-8809-4a26129efa4b.png)

Not sure why JITI is trying to mess with it 🤔 (`nuxt-hue` is compiled using `siroc` to `cjs`)

**Comment by pi0** [comment]
`JITI_DEBUG=1` might help to get some extra info.

**Comment by pi0** [comment]
I guess guessed the issue :D

**Comment by lihbr** [comment]
Awesome ♥ Yeah I think I guess it too, if that can be supported by JITI that'd be awesome ☺️

**Comment by pi0** [comment]
Can you please try against `1.12.14`? ESM resolution seems more work to be enabled by default.

**Comment by lihbr** [comment]
Works 🎉
