### ISSUE TITLE
There is require cache, although the value of `requireCache` is false.

### ISSUE THREAD

**Issue by TrickyPi** [unjs/jiti#70]
[minimal repo](https://stackblitz.com/edit/node-nrm4f6?file=index.js&view=editor)

running `node index.js`, we will see that the exports of `foo.js` is same as before, although its content is changed.

I hope i didn't misunderstand the meaning of `requireCache`.

**Comment by TrickyPi** [comment]
Thanks for you reply.
> We can introduce a new flag to jiti to avoid native require like `nativeCJSRequire: false` and disable it automatically with `requireCache: false` but I wouldn't use that because it slows down jiti and introduces edge cases.

yeah, i agree with you, using `nativeCJSRequire: false` is not a good resolution. Currently, if users want to re-require a changed file, it must not be a valid CJS and without .js extension, i wonder if we can introduce a flag that will effect Node.js cache, i used to think `requireCache` will effect Node.js cache.

**Comment by pi0** [comment]
Using native Node.js CJS, we need to invalidate the cache by ourself. See [clearRequireCahce](https://github.com/nuxt/framework/blob/d4b5ff2d9d4747d04e5a65c0f85df8bc968d5cfe/packages/kit/src/internal/cjs.ts#L28) example.

**Comment by TrickyPi** [comment]
Hmm, ok, thanks for the example link.
