### ISSUE TITLE
Root Directory Not Properly Indentified

### ISSUE THREAD

**Issue by keithlee2010** [unjs/jiti#74]
This package is used as a dependency with Nuxt.  When importing file outside the project root on a windows machine the 'readNearestPackageJSON ' function enters an **infinite loop**.  Running the same code in Linux does not present the problem.  The exit condition of the while loop is never met because root directory is misidentified.  The root is 'C:\' (not '/').  The solution is finding the root directory agnostic of the OS.  Perhaps something like this:

`path.parse(process.cwd()).root`

**Current Function:**

```
export function readNearestPackageJSON (path: string): PackageJson | undefined {
  while (path && path !== '.' && path !== '/') {
    path = join(path, '..')
    try {
      const pkg = readFileSync(join(path, 'package.json'), 'utf-8')
      try {
        return JSON.parse(pkg)
      } catch {}
      break
    } catch {}
  }
}
```

**Possible Updated Function:**
```
export function readNearestPackageJSON (path: string): PackageJson | undefined {

  const root = path.parse(process.cwd()).root;
  while (path && path !== '.' && path !== root) {
    path = join(path, '..')
    try {
      const pkg = readFileSync(join(path, 'package.json'), 'utf-8')
      try {
        return JSON.parse(pkg)
      } catch {}
      break
    } catch {}
  }
}
```

**Comment by pi0** [comment]
Thanks for reporting issue and sorry took long to address. Using [unjs/pathe](https://github.com/unjs/pathe) to fix. It handles `join('C:\\', '..')` to be `/`.
