### ISSUE TITLE
Resolved module type depends on order in package.json

### ISSUE THREAD

**Issue by tobiasdiez** [unjs/jiti#88]
Importing a package with `package.json` containing
```
"exports": {
    ".": {
      "require": "./dist/module.cjs"
      "import": "./dist/module.mjs",
    }
  },
```
resolves to the cjs version. However, importing the same package but now with the following `package.json` resolves the esm version:
```
"exports": {
    ".": {
      "import": "./dist/module.mjs",
      "require": "./dist/module.cjs"
    }
  },
``` 

I debugged it and found that the root issue is in
https://github.com/unjs/jiti/blob/64151afdda6543173615574ba8c44c893fb411e5/src/jiti.ts#L125-L128 which then calls
https://github.com/unjs/mlly/blob/5b441cec7ac0558370235105c646f48bb1334c28/lib/import-meta-resolve/resolve.js#L606-L624
For a more consistent behavior, its probably better to traverse there over the conditions and pick the key, instead of traversing over the keys and checking for the conditions.

**Comment by pi0** [comment]
Hi. We have recently fixed this. JITI always prefers require (considering internally it works with cjs natively) and import condition fallback.
