### ISSUE TITLE
ERROR  Cannot start nuxt:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by logotip4ik** [unjs/jiti#89]
Hello!
Really appreciate your work on this library.

### Description
Recently i wanted to create nuxt module for user management made possible by [lucia-auth](https://lucia-auth.vercel.app). After [setting up authentication](https://lucia-auth.vercel.app/learn/start-here/getting-started) and passing it into module options, I tried to start nuxt playground. Nuxt and nitro versions were logged to console, but then everything was frozen and after about 5 minutes error by jiti was logged.

```sh
Nuxi 3.0.0-rc.13                                                                                                   14:00:43
Nuxt 3.0.0-rc.13 with Nitro 0.6.1                                                                                  14:00:43

 ERROR  Cannot start nuxt:  Maximum call stack size exceeded                                                       14:04:43

  at jiti (node_modules\jiti\dist\jiti.js:1:247662)
  at D:/dev/nuxt-lucia-auth/node_modules/lucia-auth/auth/user/authenticate.js:1:194
  at jiti (node_modules\jiti\dist\jiti.js:1:247502)
  at D:/dev/nuxt-lucia-auth/node_modules/lucia-auth/auth/user/index.js:1:1413
  at jiti (node_modules\jiti\dist\jiti.js:1:247502)
  at D:/dev/nuxt-lucia-auth/node_modules/lucia-auth/auth/index.js:1:189
  at jiti (node_modules\jiti\dist\jiti.js:1:247502)
  at D:/dev/nuxt-lucia-auth/node_modules/lucia-auth/index.js:1:712
  at jiti (node_modules\jiti\dist\jiti.js:1:247502)
  at D:/dev/nuxt-lucia-auth/node_modules/lucia-auth/auth/session.js:1:412
```

If you try to remove use of lucia's adapter everything seams to work. Then I went to debugger, and find out that jiti was stuck in a loop where it was doing something with file extensions ? Change of adapter to for example to prisma wont help. I thought maybe yarn berry was messing something up, but the result was the same even with classic version and freshly installed dependencies. Also tried executing standalone `playground/lib/auth.ts` file with `jiti`, but it also was frozen.

### Reproduction
repo - https://github.com/logotip4ik/jiti-issue

### System info

- Operating System: `Windows_NT`
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `yarn@3.2.4`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

**Comment by pi0** [comment]
Hi. A similar issue should be fixed in recent versions of jiti. Please let me know to reopen if a fresh lockfile still reproduces the issue.

**Comment by sonofmagic** [comment]
Hello! I meet the same issue. The log is as follows:
```js
Nuxi 3.5.1                                                                                                                                                       18:03:18
Nuxt 3.5.1 with Nitro 2.4.1                                                                                                                                      18:03:18

 ERROR  Maximum call stack size exceeded                                                                                                                         18:06:56

  at C:\Users\13243\Documents\GitHub\icebreaker.top\node_modules\jiti\dist\jiti.js:1:245809
  at _interopDefault (C:\Users\13243\Documents\GitHub\icebreaker.top\node_modules\jiti\dist\jiti.js:1:246128)
  at jiti (C:\Users\13243\Documents\GitHub\icebreaker.top\node_modules\jiti\dist\jiti.js:1:248905)
  at C:/Users/13243/Documents/GitHub/icebreaker.top/apps/blog-new/node_modules/.pnpm/mlly@1.3.0/node_modules/mlly/dist/index.mjs:6:14
  at jiti (C:\Users\13243\Documents\GitHub\icebreaker.top\node_modules\jiti\dist\jiti.js:1:248468)
  at C:/Users/13243/Documents/GitHub/icebreaker.top/apps/blog-new/node_modules/.pnpm/pkg-types@1.0.3/node_modules/pkg-types/dist/index.mjs:3:13
  at jiti (C:\Users\13243\Documents\GitHub\icebreaker.top\node_modules\jiti\dist\jiti.js:1:248468)
  at C:/Users/13243/Documents/GitHub/icebreaker.top/apps/blog-new/node_modules/.pnpm/mlly@1.3.0/node_modules/mlly/dist/index.mjs:12:17
  at jiti (C:\Users\13243\Documents\GitHub\icebreaker.top\node_modules\jiti\dist\jiti.js:1:248468)
  at C:/Users/13243/Documents/GitHub/icebreaker.top/apps/blog-new/node_modules/.pnpm/pkg-types@1.0.3/node_modules/pkg-types/dist/index.mjs:3:13

error Command failed with exit code 1.
```

This error only occurred on my windows10 machine.
I try to run this repo on my Macbook pro. It starts smoothly with no error.

## Reproduction
repo - [sonofmagic/icebreaker.top/blog-new](https://github.com/sonofmagic/icebreaker.top/tree/dev/apps/blog-new)

## System info
Operating System: `Windows 10`
Node Version: `v16.14.2`
Nuxt Version: `3.5.1`
Nitro Version: `2.4.1`
Package Manager: `pnpm@8.5.1`
Builder: `vite`
